import { MetadataRoute } from 'next'

export default function sitemap(): MetadataRoute.Sitemap {
  const baseUrl = 'https://proptham.com'

  const staticRoutes = [
    '',
    '/buy',
    '/buy/apartments',
    '/buy/villas',
    '/buy/houses',
    '/buy/builder-floors',
    '/buy/ready-to-move',
    '/buy/under-construction',
    '/rent',
    '/rent/flats',
    '/rent/houses',
    '/rent/villas',
    '/projects',
    '/projects/new-launches',
    '/projects/upcoming',
    '/plots',
    '/plots/residential',
    '/plots/gated',
    '/commercial',
    '/commercial/office',
    '/commercial/retail',
    '/commercial/warehouse',
    '/compare',
    '/explore',
    '/cities',
    '/localities',
    '/top-picks',
    '/map',
    '/list-property',
    '/research',
    '/property-research',
    '/property-analysis',
    '/property-report',
    '/property-due-diligence',
    '/price-intelligence',
    '/location-analysis',
    '/commercial-intelligence',
    '/seller-intelligence',
    '/expert-consultation',
    '/how-it-works',
    '/ask',
    '/landcheck',
    '/verify',
    '/properties',
    '/builders',
    '/locations',
    '/chennai',
    '/bangalore',
    '/hyderabad',
    '/pune',
    '/mumbai',
    '/chennai/omr',
    '/chennai/velachery',
    '/chennai/sholinganallur',
    '/chennai/anna-nagar',
    '/bangalore/whitefield',
    '/bangalore/sarjapur',
    '/bangalore/hsr-layout',
    '/hyderabad/gachibowli',
    '/hyderabad/kondapur',
    '/pune/hinjewadi',
    '/pune/wakad',
    '/mumbai/thane',
    '/mumbai/navi-mumbai',
    '/guides',
    '/guides/buying',
    '/guides/due-diligence',
    '/guides/investment',
    '/guides/property-risks',
    '/insights',
    '/tools',
    '/tools/stamp-duty',
    '/tools/price-analysis',
    '/tools/land-area',
    '/methodology',
    '/trust',
    '/about',
    '/contact',
  ]

  return staticRoutes.map((route) => ({
    url: `${baseUrl}${route}`,
    lastModified: new Date().toISOString().split('T')[0],
    changeFrequency: 'weekly',
    priority: route === '' ? 1.0 : 0.8,
  }))
}
